### PR TITLE
Add temporary support for macOS 10.12.

### PR DESCRIPTION
**Pull request by nobu417**
Temporary support for macOS 10.12 Beta 1.
Added quick fix to function to define version of macOS, now it works on 10.12 Beta 1.

### CODE REVIEW

**Comment by ChrisJohnsen** [comment]
Thanks!

I have merged this into the `pu` (proposed updates) branch along with changes to the version string and the supported OSes string. When I get confirmation that this still works (and is necessary) or when we get closer to the release of macOS Sierra I will move it into the `master` branch.

Please let me know if the wrapper program is still actually necessary for [other (non-pasteboard) services][bpb] (or if there has been a macOS regression and the wrapper is once again necessary for pasteboard access under *tmux*—it was not necessary under 10.10 or 10.11).

[bpb]: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/blob/master/Usage.md#beyond-pasteboard-access

A quick way to test might be to run `osascript -e 'display dialog "testing"'` in a plain terminal window (no *tmux*), inside a *tmux* plain session (no wrapper), and inside a *tmux* session with the wrapper. The first should always work. If the second works then the wrapper program may no not be necessary on Sierra (at least for this kind of access). If the last one fails then the wrapper program is not effective on Sierra.

**Comment by nobu417** [comment]
Here's quick reply about your question.

Under the environment of El Capitan, the wrapper program was unnecessary in fact. So I was not using the wrapper program under the environment of El Capitan, though I was using it until Yosemite. But just after installed macOS Sierra, on Emacs in tmux, Emacs's error says that pbcopy cannot be successful without the wrapper program.

**Comment by ChrisJohnsen** [comment]
Hmm, I wonder if Apple reverted their partial support for accessing this stuff that they had in 10.10 and 10.11. Are you using a package for your Emacs+pasteboard configuration? Doing a quick `grep -FR pbcopy /path/to/Emacs.app` did not turn up anything for me (24.5-1 from [Emacs For OS X][e4o]). Maybe fancier distributions (Aquamacs?) include something that uses *pbcopy*?

[e4o]: https://emacsforosx.com/

Let’s let Apple make a few more beta releases to make sure nothing else changes. I’ll refer anyone needing Sierra support to the [`pu` branch][pu] for now. I would guess the final release will be in September/October, so I will plan for a merge to `master` around August.

[pu]: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/tree/pu

**Comment by nobu417** [comment]
Oh, as you thought, my distribution of Emacs is my own build (because I need some patches relating to Japanese). That may be the reason why I need the wrapper program under the environment of tmux . I tried your suggestion "grep -FR pbcopy /path/to/Emacs.app" and then nothing returned.

As you suggested, someone who uses their own build of Emacs need this wrapper such me. I think this is a great wrapper program for me and those people.

It's not necessary to use this wrapper for people who use the official build of Emacs for Mac, however there are people like me who use emacs which's not official build for macOS, and it's very useful for people like me. Why don't we continue this project for those people?

I'm sure to support this project if there's someone who need this. My code that I donated is very small. But I'm happy that if there's someone who need this.

**Comment by ChrisJohnsen** [comment]
I don’t plan to close the project, so you should not worry about that. I would just like to delay a new release until the Sierra beta has progressed a bit further; hopefully this will reduce the chance of Apple changing something that would require new code in the wrapper (and an extra release). Sierra beta users can use “2.4+” from the `pu` branch until the wrapper changes are released on `master` as “2.5” (which should happen before a post-beta Sierra is released).

When you wrote

> … Emacs's error says that pbcopy cannot be successful without the wrapper program.

I was curious if there was an Emacs package or distribution that used or recommended using the wrapper program; that may have been a overly literal interpretation of what you wrote (i.e. that the Emacs error message actually mentioned *pbcopy* and the wrapper program). It was not important I was just idly curious.

**Comment by bosr** [comment]
Hi, thanks for the discussion!

The `osascript ...` test you provide above succeeds in both the terminal and an unwrapped tmux, however in a unwrapped tmux, the system copy/paste (using unwrapped `/usr/bin/pb*`) and open commands (as in `open doc.pdf`) fail: 
```
~ ❯❯❯ osascript -e 'display dialog "testing"'  # the dialog opens
button returned:OK
~ ❯❯❯ open ~/Downloads/doc.pdf
The window server could not be contacted.  open must be run with a user logged in at the console, either as that user or as root.
~ ❯❯❯ echo 'foo' | /usr/bin/pbcopy
~ ❯❯❯ /usr/bin/pbpaste
~ ❯❯❯
```
So I guess the wrapper is necessary, at least for the moment.

**Comment by ChrisJohnsen** [comment]
@bosr Thanks for the info! Are your results also from a Sierra beta?

Since `display dialog` never seemed to fail in your test (nor in my (belated) testing), it seems to be a poor diagnostic tool. The idea was based on the command from #40. I tested it on 10.11 before posting, but “simplified” it from `display notification` to `display message` without re-testing. I assume that they used the same mechanism to do talk to the GUI, but you have shown that assumption to be incorrect. Under 10.11 `osascript -e 'display notification "testing"'` fails under *tmux* unless I “wrap” it while the similar use of `display dialog` always seems to work (plain terminal, non-wrapped in *tmux*, wrapped in *tmux*).

**Comment by bosr** [comment]
Thanks Chris for the info. Yes I ran those commands on a beta version of macOS Sierra. Your wrapper still works great, so as you suggest, let's wait and see as it stabilizes.  

Cheers

**Comment by zchee** [comment]
@ChrisJohnsen @nobu417 
I was testing that pull-request on a macOS Sierra. it will works.
tmux copy-mode are works fine, but vim register sync to clipboard does not work without tmux-MacOSX-pasteboard.
Thanks!

**Comment by bosr** [comment]
Same for me, tmux and vim copy/paste work perfectly with the current PR. Thanks

**Comment by mvanbaak** [comment]
Please merge to master for brew users:

`brew install --HEAD reattach-to-user-namespace`

**Comment by ChrisJohnsen** [comment]
If someone can confirm that this still works on the latest developer beta 4 release, then I will push a new `master` branch and `v2.5` tag.

Thanks!

**Comment by nobu417** [comment]
This works on the Sierra developer beta 4 which was released yesterday with no problem as well.

It may be almost time to merge this to master :-P

**Pull request merged**
